services:
  - type: web
    name: gsu-attendance-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: LOG_LEVEL
        value: DEBUG
      - key: TZ
        value: America/Chicago
